"""
Reusable Gmail HTML report sender for automated pipelines.

This module handles SMTP credentials, MIMEMultipart message construction, and
exponential backoff retry logic. Use it in any project that needs to send an
HTML report to an inbox via Gmail.

No external dependencies — only stdlib (smtplib, ssl, email, re).
"""

import re
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def is_configured(sender: str, app_password: str, recipients: str | list) -> bool:
    """
    Check if Gmail credentials and recipients are minimally configured.

    Returns False if any value is empty/None, allowing callers to gracefully
    skip sending during local dev or before CI secrets are set up.

    Args:
        sender: Gmail address to send from (e.g., "your-email@gmail.com")
        app_password: Gmail App Password (generate at myaccount.google.com/apppasswords)
        recipients: Comma-separated email list (str) or list of addresses

    Returns:
        True if all three are non-empty, False otherwise.
    """
    if not sender or not app_password:
        return False

    if isinstance(recipients, str):
        recipients = [x.strip() for x in recipients.split(",") if x.strip()]

    return len(recipients) > 0


def _auto_plaintext(html_body: str) -> str:
    """
    Auto-generate a plaintext fallback by stripping HTML tags from html_body.

    Simple regex-based approach: removes <...> and common HTML entities.
    Suitable for plain-text email fallback when a hand-written version is not
    available.
    """
    text = re.sub(r"<[^>]+>", "", html_body)  # strip HTML tags
    text = re.sub(r"&nbsp;", " ", text)
    text = re.sub(r"&lt;", "<", text)
    text = re.sub(r"&gt;", ">", text)
    text = re.sub(r"&amp;", "&", text)
    text = re.sub(r"\n\s*\n", "\n\n", text)  # collapse multiple blank lines
    return text.strip()


def _parse_recipients(raw: str | list) -> list[str]:
    """
    Parse recipients into a list of email addresses.

    Args:
        raw: Comma-separated string (e.g., "a@ex.com, b@ex.com") or a list

    Returns:
        List of stripped, non-empty email addresses.
    """
    if isinstance(raw, list):
        return [x.strip() for x in raw if isinstance(x, str) and x.strip()]
    return [x.strip() for x in raw.split(",") if x.strip()]


def send_html_report(
    subject: str,
    html_body: str,
    sender: str,
    app_password: str,
    recipients: str | list,
    text_body: str | None = None,
    max_attempts: int = 3,
) -> None:
    """
    Send an HTML report via Gmail SMTP with exponential backoff retry.

    Constructs a MIMEMultipart message with both plaintext and HTML parts (for
    email clients that prefer text), handles SMTP connection with retry logic,
    and raises an exception if the send ultimately fails.

    Authentication errors are re-raised immediately (permanent, no retry).
    Transient errors (timeouts, temp SMTP errors) retry with exponential backoff,
    then raise after max_attempts is exceeded.

    Args:
        subject: Email subject line
        html_body: HTML content (required)
        sender: Gmail sender address (e.g., "your-email@gmail.com")
        app_password: Gmail App Password (from myaccount.google.com/apppasswords)
        recipients: Comma-separated email string or list of addresses
        text_body: Plaintext fallback. If None, auto-generated by stripping HTML tags.
        max_attempts: Number of SMTP connection attempts (default 3)

    Raises:
        ValueError: If sender, app_password, or recipients are empty
        smtplib.SMTPAuthenticationError: If Gmail credentials are invalid (no retry)
        Exception: If sending fails after max_attempts (final attempt exception is re-raised)

    Example:
        from gmail_notifier import send_html_report

        html = "<h1>Report</h1><p>Your data here</p>"
        send_html_report(
            subject="Weekly Report",
            html_body=html,
            sender="bot@gmail.com",
            app_password="your-app-password",
            recipients="you@example.com",
        )
    """
    if not sender or not app_password:
        raise ValueError("sender and app_password are required")

    recipients_list = _parse_recipients(recipients)
    if not recipients_list:
        raise ValueError("recipients list is empty")

    if text_body is None:
        text_body = _auto_plaintext(html_body)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(recipients_list)
    msg.attach(MIMEText(text_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    last_exc = None
    for attempt in range(max_attempts):
        try:
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
                server.login(sender, app_password)
                server.sendmail(sender, recipients_list, msg.as_string())
            return
        except smtplib.SMTPAuthenticationError as e:
            raise e from None
        except Exception as e:
            last_exc = e
            if attempt < max_attempts - 1:
                wait_sec = 5 * (2 ** attempt)
                print(
                    f"[SMTP] Attempt {attempt + 1}/{max_attempts} failed: {e}. "
                    f"Retrying in {wait_sec}s..."
                )
                import time
                time.sleep(wait_sec)
            else:
                print(f"[SMTP] All {max_attempts} attempts failed. Final error: {e}")

    raise last_exc
